/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package exam;

import java.awt.CardLayout;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;

/**
 *
 * @author ICT-000
 */
public class BoardDemo extends javax.swing.JFrame {

	private static final long serialVersionUID = 1L;
	private int num = 1;
	private static final java.util.logging.Logger logger = java.util.logging.Logger
			.getLogger(BoardDemo.class.getName());
	private CardLayout card;
	private BoardService blist;//

	public BoardDemo() {
		initComponents();
		card = (CardLayout) pp.getLayout();
		card.show(pp, "c2");
		blist = new BoardService();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		pp = new javax.swing.JPanel();
		boardList = new javax.swing.JPanel();
		jScrollPane1 = new javax.swing.JScrollPane();
		jTextArea1 = new javax.swing.JTextArea();
		addBtn = new javax.swing.JButton();
		boardForm = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		subject = new javax.swing.JTextField();
		jLabel3 = new javax.swing.JLabel();
		writer = new javax.swing.JTextField();
		jScrollPane2 = new javax.swing.JScrollPane();
		contents = new javax.swing.JTextArea();
		jButton1 = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		pp.setLayout(new java.awt.CardLayout());

		boardList.setBackground(new java.awt.Color(255, 255, 102));

		jTextArea1.setColumns(20);
		jTextArea1.setRows(5);
		jScrollPane1.setViewportView(jTextArea1);

		addBtn.setBackground(new java.awt.Color(255, 204, 102));
		addBtn.setText("Add");
		addBtn.addActionListener(this::addBtnActionPerformed);

		javax.swing.GroupLayout boardListLayout = new javax.swing.GroupLayout(boardList);
		boardList.setLayout(boardListLayout);
		boardListLayout
				.setHorizontalGroup(boardListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(boardListLayout.createSequentialGroup().addGap(16, 16, 16)
								.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 690,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addContainerGap(22, Short.MAX_VALUE))
						.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
								boardListLayout.createSequentialGroup()
										.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(addBtn).addGap(37, 37, 37)));
		boardListLayout.setVerticalGroup(boardListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(boardListLayout.createSequentialGroup().addGap(14, 14, 14)
						.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 398,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED).addComponent(addBtn)
						.addContainerGap(25, Short.MAX_VALUE)));

		pp.add(boardList, "c1");

		boardForm.setBackground(new java.awt.Color(255, 153, 102));

		jLabel1.setFont(new java.awt.Font("맑은 고딕", 1, 24)); // NOI18N
		jLabel1.setText("Board Form");

		jLabel2.setText("제목 :");

		jLabel3.setText("작성자 :");

		contents.setColumns(20);
		contents.setRows(5);
		jScrollPane2.setViewportView(contents);

		jButton1.setText("Save");
		jButton1.addActionListener(this::jButton1ActionPerformed);

		jButton2.setText("List");
		jButton2.addActionListener(this::jButton2ActionPerformed);

		javax.swing.GroupLayout boardFormLayout = new javax.swing.GroupLayout(boardForm);
		boardForm.setLayout(boardFormLayout);
		boardFormLayout.setHorizontalGroup(boardFormLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(boardFormLayout.createSequentialGroup().addGroup(boardFormLayout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(boardFormLayout.createSequentialGroup().addGap(30, 30, 30).addComponent(jLabel1,
								javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGroup(boardFormLayout.createSequentialGroup().addGap(35, 35, 35)
								.addGroup(
										boardFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
												.addComponent(jLabel3).addComponent(jLabel2))
								.addGap(18, 18, 18)
								.addGroup(boardFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(subject, javax.swing.GroupLayout.PREFERRED_SIZE, 201,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(writer, javax.swing.GroupLayout.PREFERRED_SIZE, 136,
												javax.swing.GroupLayout.PREFERRED_SIZE)))
						.addGroup(boardFormLayout.createSequentialGroup().addGap(41, 41, 41).addComponent(jScrollPane2,
								javax.swing.GroupLayout.PREFERRED_SIZE, 649, javax.swing.GroupLayout.PREFERRED_SIZE)))
						.addContainerGap(38, Short.MAX_VALUE))
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
						boardFormLayout.createSequentialGroup().addGap(0, 0, Short.MAX_VALUE).addComponent(jButton1)
								.addGap(18, 18, 18).addComponent(jButton2).addGap(55, 55, 55)));
		boardFormLayout.setVerticalGroup(boardFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(boardFormLayout.createSequentialGroup().addGap(18, 18, 18)
						.addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(18, 18, 18)
						.addGroup(boardFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel2).addComponent(subject, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(35, 35, 35)
						.addGroup(boardFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel3).addComponent(writer, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 127,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
						.addGroup(boardFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jButton1).addComponent(jButton2))
						.addGap(70, 70, 70)));

		pp.add(boardForm, "c2");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(pp,
				javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(pp,
				javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_addBtnActionPerformed
		
		card.show(pp, "c2");
	}// GEN-LAST:event_addBtnActionPerformed

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
		BoardVO v = new BoardVO();
		v.setNum(num++);
		v.setSubject(subject.getText());
		v.setWriter(writer.getText());
		v.setContents(contents.getText());
		v.setBdate(new SimpleDateFormat("yyyy-MM-dd").format(new Date()));
		blist.addBoard(v);

		
		
		jTextArea1.setText("");
		ArrayList<BoardVO> listv = blist.getList();
		for (BoardVO e : listv) {
			jTextArea1.append(e.getNum() + ":" + e.getSubject() + ":" + e.getWriter() + "\n");
		}
	}// GEN-LAST:event_jButton1ActionPerformed

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton2ActionPerformed
		// TODO add your handling code here:
		card.show(pp, "c1");
	}// GEN-LAST:event_jButton2ActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
			logger.log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(() -> new BoardDemo().setVisible(true));
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton addBtn;
	private javax.swing.JPanel boardForm;
	private javax.swing.JPanel boardList;
	private javax.swing.JTextArea contents;
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JScrollPane jScrollPane2;
	private javax.swing.JTextArea jTextArea1;
	private javax.swing.JPanel pp;
	private javax.swing.JTextField subject;
	private javax.swing.JTextField writer;
	// End of variables declaration//GEN-END:variables
}
